seed: 0
output_dir: ./st_mem
exp_name: finetune
resume: null
start_epoch: 0
encoder_path: ./pretrain/encoder.pth
model_name: st_mem_vit_base
mode: finetune
device: cuda

ddp:
  world_size: 1
  rank: -1
  gpu: 0
  dist_url: env://
  dist_backend: nccl
  distributed: false

model:
  seq_len: 6000
  patch_size: 75
  num_leads: 6
  num_classes: 2

dataset:
  filename_col: FILE_NAME
  fs_col: SAMPLE_RATE
  label_col: LABEL
  label_dtype: long
  lead: limb_lead
  fs: 500
  index_dir: ./data
  ecg_dir: ./data/processed_ecg_PAP #change data path for other downstream tasks

  train_csv: train_PAP.csv
  valid_csv: val_PAP.csv
  test_csv: val_PAP.csv

  rand_augment:
    use: true
    kwargs:
      op_names:
      - shift
      - cutout
      - drop
      - flip
      - erase
      - sine
      - partial_sine
      - partial_white_noise
      level: 10
      num_layers: 2
      prob: 0.5

  train_transforms:
  - random_crop:
      crop_length: 6000
  - highpass_filter:
      fs: 500
      cutoff: 0.67
      order: 5
  - lowpass_filter:
      fs: 500
      cutoff: 40
      order: 5
  - standardize:
      axis: [0, 1]

  eval_transforms:
  - n_crop:
      crop_length: 6000
      num_segments: 3
  - highpass_filter:
      fs: 500
      cutoff: 0.67
      order: 5
  - lowpass_filter:
      fs: 500
      cutoff: 40
      order: 5
  - standardize:
      axis: [0, 1]

dataloader:
  batch_size: 32
  num_workers: 8
  pin_memory: True

train:
  epochs: 10
  accum_iter: 1
  warmup_epochs: 3
  min_lr: 0
  blr: 1.0e-3
  lr: null
  weight_decay: 0.05
  dist_eval: false
  max_norm: null
  optimizer: adamw

loss:
  name: cross_entropy

metric:
  task: binary
  compute_on_cpu: true
  sync_on_compute: false
  num_classes: 2
  target_metrics:
  - Accuracy
  - F1Score
  - AUROC
  - MCC

test:
  target_metric: loss
